version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install -r requirements.txt
  
  build:
    commands:
      - echo "Running tests..."
      - python -m pytest tests/ --cov=app --cov-report=term --cov-report=html -v
      - echo "Tests completed"
      - echo "Creating deployment package..."
      - zip -r application.zip . -x "*.git*" "*__pycache__*" "*.pytest_cache*" "htmlcov/*" "*.db" ".coverage" "*venv/*" "*.venv/*"
      - echo "Artifact created"

artifacts:
  files:
    - application.zip
  name: application-$(date +%Y%m%d-%H%M%S).zip

reports:
  pytest_reports:
    files:
      - 'htmlcov/**/*'
    file-format: HTML
    base-directory: 'htmlcov'

cache:
  paths:
    - '/root/.cache/pip/**/*'
